SELECT INFO.ID, NAME.FISH_NAME, INFO.LENGTH FROM FISH_INFO INFO 
    INNER JOIN FISH_NAME_INFO NAME ON INFO.FISH_TYPE = NAME.FISH_TYPE 
    WHERE (INFO.FISH_TYPE, INFO.LENGTH) IN 
    (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE) 
    ORDER BY ID;